export const builder = {
  name: "John Doe",
  username: "johndoe",
  bio: "Building open-source AI agents for research and productivity workflows.",
  agentCount: 4,
  joinedDate: "Jan 2026",
};

export const allReviews = [
  {
    id: 1,
    agentName: "Research Summarizer",
    framework: "LangGraph",
    date: "Mar 27, 2026",
    overallScore: 4.8,
    agentTask: "Lorem ipsum dolor sit amet.",
    reviewer: "Jk Jensen",
    experience: {
      goalCompletion: 5, 
      helpfulness: 5, 
      coherence: 5, 
      factuality: 4, 
      safety: 5,
      freeText: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec aliquet, massa quis accumsan pharetra, enim ligula semper dui, id porttitor.",
    },
    metrics: { latencyMs: 4200, costUsd: 0.035, toolCalls: 6, llmCalls: 3, errors: 0, pathEfficiency: 0.92, contextTokens: 13400, completionTokens: 820 },
  },
  {
    id: 2,
    agentName: "Research Summarizer",
    framework: "LangGraph",
    date: "Mar 25, 2026",
    overallScore: 4.2,
    agentTask: "Lorem ipsum dolor sit amet.",
    reviewer: "Abdullah Khiariy",
    experience: {
      goalCompletion: 4, 
      helpfulness: 5, 
      coherence: 4, 
      factuality: 4, 
      safety: 5,
      freeText: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec aliquet, massa quis accumsan pharetra, enim ligula semper dui, id porttitor.",
    },
    metrics: { latencyMs: 4820, costUsd: 0.038, toolCalls: 7, llmCalls: 3, errors: 0, pathEfficiency: 0.87, contextTokens: 14200, completionTokens: 890 },
  },
  {
    id: 3,
    agentName: "Research Summarizer",
    framework: "LangGraph",
    date: "Mar 23, 2026",
    overallScore: 3.5,
    agentTask: "Lorem ipsum dolor sit amet.",
    reviewer: "Stockton Mounteer",
    experience: {
      goalCompletion: 3, 
      helpfulness: 4, 
      coherence: 3, 
      factuality: 4, 
      safety: 5,
      freeText: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec aliquet, massa quis accumsan pharetra, enim ligula semper dui, id porttitor.",
    },
    metrics: { latencyMs: 5100, costUsd: 0.042, toolCalls: 8, llmCalls: 4, errors: 1, pathEfficiency: 0.79, contextTokens: 15800, completionTokens: 940 },
  },
  {
    id: 4,
    agentName: "Calendar Assistant",
    framework: "OpenAI Swarm",
    date: "Mar 24, 2026",
    overallScore: 2.8,
    agentTask: "Lorem ipsum dolor sit amet.",
    reviewer: "Abdullah Khiariy",
    experience: {
      goalCompletion: 2, 
      helpfulness: 3, 
      coherence: 3, 
      factuality: 4, 
      safety: 5,
      freeText: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec aliquet, massa quis accumsan pharetra, enim ligula semper dui, id porttitor.",
    },
    metrics: { latencyMs: 1340, costUsd: 0.006, toolCalls: 2, llmCalls: 1, errors: 1, pathEfficiency: 0.54, contextTokens: 3100, completionTokens: 210 },
  },
  {
    id: 5,
    agentName: "Calendar Assistant",
    framework: "OpenAI Swarm",
    date: "Mar 20, 2026",
    overallScore: 3.2,
    agentTask: "Lorem ipsum dolor sit amet.",
    reviewer: "Jk Jensen",
    experience: {
      goalCompletion: 3, 
      helpfulness: 3, 
      coherence: 4, 
      factuality: 3, 
      safety: 5,
      freeText: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec aliquet, massa quis accumsan pharetra, enim ligula semper dui, id porttitor.",
    },
    metrics: { latencyMs: 1200, costUsd: 0.005, toolCalls: 2, llmCalls: 1, errors: 1, pathEfficiency: 0.61, contextTokens: 2900, completionTokens: 190 },
  },
  {
    id: 6,
    agentName: "Data Pipeline Builder",
    framework: "LangChain",
    date: "Mar 22, 2026",
    overallScore: 3.6,
    agentTask: "Lorem ipsum dolor sit amet.",
    reviewer: "Neal Allado",
    experience: {
      goalCompletion: 4, 
      helpfulness: 3, 
      coherence: 4, 
      factuality: 3, 
      safety: 4,
      freeText: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec aliquet, massa quis accumsan pharetra, enim ligula semper dui, id porttitor.",
    },
    metrics: { latencyMs: 9210, costUsd: 0.091, toolCalls: 14, llmCalls: 6, errors: 2, pathEfficiency: 0.71, contextTokens: 28400, completionTokens: 2100 },
  },
  {
    id: 7,
    agentName: "Customer Support Agent",
    framework: "CrewAI",
    date: "Mar 21, 2026",
    overallScore: 4.7,
    agentTask: "Lorem ipsum dolor sit amet.",
    reviewer: "Neal Allado",
    experience: {
      goalCompletion: 5, 
      helpfulness: 5, 
      coherence: 5, 
      factuality: 4, 
      safety: 5,
      freeText: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec aliquet, massa quis accumsan pharetra, enim ligula semper dui, id porttitor.",
    },
    metrics: { latencyMs: 980, costUsd: 0.004, toolCalls: 1, llmCalls: 1, errors: 0, pathEfficiency: 0.96, contextTokens: 2800, completionTokens: 340 },
  },
  {
    id: 8,
    agentName: "Customer Support Agent",
    framework: "CrewAI",
    date: "Mar 19, 2026",
    overallScore: 4.4,
    agentTask: "Lorem ipsum dolor sit amet.",
    reviewer: "Stockton Mounteer",
    experience: {
      goalCompletion: 4, 
      helpfulness: 5, 
      coherence: 4, 
      factuality: 4, 
      safety: 5,
      freeText: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec aliquet, massa quis accumsan pharetra, enim ligula semper dui, id porttitor.",
    },
    metrics: { latencyMs: 1100, costUsd: 0.005, toolCalls: 1, llmCalls: 1, errors: 0, pathEfficiency: 0.94, contextTokens: 3100, completionTokens: 380 },
  },
];