export const allReviews = [
  {
    id: 1,
    builderUsername: "alexrivera",
    agentName: "Research Summarizer",
    framework: "LangGraph",
    date: "Mar 27, 2026",
    overallScore: 4.8,
    agentTask: "Summarize recent ML papers on retrieval-augmented generation into a structured report.",
    reviewer: "Priya Nair",
    experience: {
      goalCompletion: 5, helpfulness: 5, coherence: 5, factuality: 4, safety: 5,
      freeText: "Significantly better than last time I used it. Citations were accurate and the summary was genuinely useful.",
    },
    metrics: { latencyMs: 4200, costUsd: 0.035, toolCalls: 6, llmCalls: 3, errors: 0, pathEfficiency: 0.92, contextTokens: 13400, completionTokens: 820 },
  },
  {
    id: 2,
    builderUsername: "alexrivera",
    agentName: "Research Summarizer",
    framework: "LangGraph",
    date: "Mar 25, 2026",
    overallScore: 4.2,
    agentTask: "Compile a literature review on climate tipping points from the last five years.",
    reviewer: "Maya Chen",
    experience: {
      goalCompletion: 4, helpfulness: 5, coherence: 4, factuality: 4, safety: 5,
      freeText: "Did a thorough job pulling together sources. Missed one key paper but the overall summary was well-structured.",
    },
    metrics: { latencyMs: 4820, costUsd: 0.038, toolCalls: 7, llmCalls: 3, errors: 0, pathEfficiency: 0.87, contextTokens: 14200, completionTokens: 890 },
  },
  {
    id: 3,
    builderUsername: "alexrivera",
    agentName: "Research Summarizer",
    framework: "LangGraph",
    date: "Mar 23, 2026",
    overallScore: 3.5,
    agentTask: "Summarize academic sources on LLM hallucination for a thesis introduction.",
    reviewer: "Chris Anand",
    experience: {
      goalCompletion: 3, helpfulness: 4, coherence: 3, factuality: 4, safety: 5,
      freeText: "Decent output but it hallucinated a citation. Had to verify everything manually.",
    },
    metrics: { latencyMs: 5100, costUsd: 0.042, toolCalls: 8, llmCalls: 4, errors: 1, pathEfficiency: 0.79, contextTokens: 15800, completionTokens: 940 },
  },
  {
    id: 4,
    builderUsername: "alexrivera",
    agentName: "Calendar Assistant",
    framework: "OpenAI Swarm",
    date: "Mar 24, 2026",
    overallScore: 2.8,
    agentTask: "Schedule a 45-minute team sync with four colleagues across different time zones.",
    reviewer: "James Park",
    experience: {
      goalCompletion: 2, helpfulness: 3, coherence: 3, factuality: 4, safety: 5,
      freeText: "Booked the wrong time zone without asking. Had to manually fix the event.",
    },
    metrics: { latencyMs: 1340, costUsd: 0.006, toolCalls: 2, llmCalls: 1, errors: 1, pathEfficiency: 0.54, contextTokens: 3100, completionTokens: 210 },
  },
  {
    id: 5,
    builderUsername: "alexrivera",
    agentName: "Calendar Assistant",
    framework: "OpenAI Swarm",
    date: "Mar 20, 2026",
    overallScore: 3.2,
    agentTask: "Book a recurring weekly standup for the product team every Monday at 9am.",
    reviewer: "Dana Kim",
    experience: {
      goalCompletion: 3, helpfulness: 3, coherence: 4, factuality: 3, safety: 5,
      freeText: "Got the time right but scheduled over an existing event. Basic conflict detection would help.",
    },
    metrics: { latencyMs: 1200, costUsd: 0.005, toolCalls: 2, llmCalls: 1, errors: 1, pathEfficiency: 0.61, contextTokens: 2900, completionTokens: 190 },
  },
  {
    id: 6,
    builderUsername: "jordanwells",
    agentName: "Data Pipeline Builder",
    framework: "LangChain",
    date: "Mar 22, 2026",
    overallScore: 3.6,
    agentTask: "Build a pipeline that ingests CSV sales data and outputs a cleaned summary table.",
    reviewer: "Sofia Reyes",
    experience: {
      goalCompletion: 4, helpfulness: 3, coherence: 4, factuality: 3, safety: 4,
      freeText: "Generated a working pipeline but used a deprecated pandas API. Had to patch two functions.",
    },
    metrics: { latencyMs: 9210, costUsd: 0.091, toolCalls: 14, llmCalls: 6, errors: 2, pathEfficiency: 0.71, contextTokens: 28400, completionTokens: 2100 },
  },
  {
    id: 7,
    builderUsername: "jordanwells",
    agentName: "Data Pipeline Builder",
    framework: "LangChain",
    date: "Mar 18, 2026",
    overallScore: 4.1,
    agentTask: "Ingest JSON logs from three sources and output a deduplicated event timeline.",
    reviewer: "Tom Nguyen",
    experience: {
      goalCompletion: 4, helpfulness: 4, coherence: 4, factuality: 4, safety: 5,
      freeText: "Handled the deduplication well. Minor formatting issues in the output table but nothing breaking.",
    },
    metrics: { latencyMs: 7800, costUsd: 0.074, toolCalls: 11, llmCalls: 5, errors: 1, pathEfficiency: 0.81, contextTokens: 22100, completionTokens: 1740 },
  },
  {
    id: 8,
    builderUsername: "jordanwells",
    agentName: "Web Scraper Agent",
    framework: "LangChain",
    date: "Mar 21, 2026",
    overallScore: 4.4,
    agentTask: "Scrape product prices from five e-commerce pages and return a comparison table.",
    reviewer: "Leila Moss",
    experience: {
      goalCompletion: 5, helpfulness: 4, coherence: 4, factuality: 4, safety: 5,
      freeText: "Worked really well. Got all five pages and the table was clean. Took a bit longer than expected.",
    },
    metrics: { latencyMs: 6400, costUsd: 0.058, toolCalls: 10, llmCalls: 4, errors: 0, pathEfficiency: 0.88, contextTokens: 18700, completionTokens: 1200 },
  },
  {
    id: 9,
    builderUsername: "jordanwells",
    agentName: "Email Drafter",
    framework: "LangChain",
    date: "Mar 19, 2026",
    overallScore: 3.9,
    agentTask: "Draft a follow-up email to a client after a missed meeting.",
    reviewer: "Chris Anand",
    experience: {
      goalCompletion: 4, helpfulness: 4, coherence: 4, factuality: 4, safety: 4,
      freeText: "Solid draft but slightly too formal for our company's tone. Easy to edit from though.",
    },
    metrics: { latencyMs: 1800, costUsd: 0.012, toolCalls: 1, llmCalls: 2, errors: 0, pathEfficiency: 0.91, contextTokens: 4200, completionTokens: 480 },
  },
  {
    id: 10,
    builderUsername: "priyanair",
    agentName: "Document Classifier",
    framework: "LangGraph",
    date: "Mar 26, 2026",
    overallScore: 4.6,
    agentTask: "Classify a batch of 40 contracts into categories: NDA, SLA, employment, or other.",
    reviewer: "Maya Chen",
    experience: {
      goalCompletion: 5, helpfulness: 5, coherence: 4, factuality: 5, safety: 5,
      freeText: "Classified all 40 correctly except one edge case. Saved hours of manual sorting.",
    },
    metrics: { latencyMs: 3200, costUsd: 0.029, toolCalls: 5, llmCalls: 3, errors: 0, pathEfficiency: 0.94, contextTokens: 11800, completionTokens: 640 },
  },
  {
    id: 11,
    builderUsername: "priyanair",
    agentName: "Document Classifier",
    framework: "LangGraph",
    date: "Mar 20, 2026",
    overallScore: 4.0,
    agentTask: "Sort 20 support tickets by urgency level: critical, high, medium, or low.",
    reviewer: "James Park",
    experience: {
      goalCompletion: 4, helpfulness: 4, coherence: 4, factuality: 4, safety: 5,
      freeText: "Good overall. Two tickets were miscategorized as medium when they should have been high.",
    },
    metrics: { latencyMs: 2800, costUsd: 0.024, toolCalls: 4, llmCalls: 2, errors: 0, pathEfficiency: 0.89, contextTokens: 9400, completionTokens: 510 },
  },
  {
    id: 12,
    builderUsername: "priyanair",
    agentName: "Meeting Summarizer",
    framework: "LangGraph",
    date: "Mar 17, 2026",
    overallScore: 4.7,
    agentTask: "Summarize a 90-minute product planning meeting transcript into action items and decisions.",
    reviewer: "Priya Nair",
    experience: {
      goalCompletion: 5, helpfulness: 5, coherence: 5, factuality: 4, safety: 5,
      freeText: "Pulled out every action item correctly. The decisions section was concise and accurate.",
    },
    metrics: { latencyMs: 3900, costUsd: 0.041, toolCalls: 3, llmCalls: 3, errors: 0, pathEfficiency: 0.95, contextTokens: 16200, completionTokens: 980 },
  },
  {
    id: 13,
    builderUsername: "sofiareyes",
    agentName: "SQL Query Agent",
    framework: "CrewAI",
    date: "Mar 25, 2026",
    overallScore: 3.8,
    agentTask: "Write a SQL query to find the top 10 customers by revenue in Q1 2026.",
    reviewer: "Tom Nguyen",
    experience: {
      goalCompletion: 4, helpfulness: 4, coherence: 4, factuality: 3, safety: 4,
      freeText: "Query ran without errors but used a suboptimal join. Rewrote it for performance but the logic was right.",
    },
    metrics: { latencyMs: 2100, costUsd: 0.018, toolCalls: 3, llmCalls: 2, errors: 0, pathEfficiency: 0.82, contextTokens: 6800, completionTokens: 420 },
  },
  {
    id: 14,
    builderUsername: "sofiareyes",
    agentName: "Report Generator",
    framework: "CrewAI",
    date: "Mar 22, 2026",
    overallScore: 4.3,
    agentTask: "Generate a weekly performance report from sales metrics for the executive team.",
    reviewer: "Leila Moss",
    experience: {
      goalCompletion: 4, helpfulness: 5, coherence: 4, factuality: 4, safety: 5,
      freeText: "Clean output with good structure. Charts were referenced correctly. Minor typo in the header.",
    },
    metrics: { latencyMs: 5600, costUsd: 0.052, toolCalls: 8, llmCalls: 4, errors: 0, pathEfficiency: 0.86, contextTokens: 19200, completionTokens: 1480 },
  },
  {
    id: 15,
    builderUsername: "marcustan",
    agentName: "Symptom Triage Agent",
    framework: "LangGraph",
    date: "Mar 16, 2026",
    overallScore: 4.5,
    agentTask: "Given a list of reported symptoms, suggest likely conditions and recommended next steps.",
    reviewer: "Dana Kim",
    experience: {
      goalCompletion: 5, helpfulness: 4, coherence: 5, factuality: 4, safety: 5,
      freeText: "Appropriately cautious and recommended professional consultation at every step. Suggestions were sensible.",
    },
    metrics: { latencyMs: 2600, costUsd: 0.022, toolCalls: 2, llmCalls: 2, errors: 0, pathEfficiency: 0.93, contextTokens: 7400, completionTokens: 560 },
  },
  {
    id: 16,
    builderUsername: "danakim",
    agentName: "Customer Support Agent",
    framework: "CrewAI",
    date: "Mar 21, 2026",
    overallScore: 4.7,
    agentTask: "Handle a customer complaint about a delayed refund and provide a resolution.",
    reviewer: "Tom Nguyen",
    experience: {
      goalCompletion: 5, helpfulness: 5, coherence: 5, factuality: 4, safety: 5,
      freeText: "Handled the query without escalating unnecessarily. Tone was firm but empathetic.",
    },
    metrics: { latencyMs: 980, costUsd: 0.004, toolCalls: 1, llmCalls: 1, errors: 0, pathEfficiency: 0.96, contextTokens: 2800, completionTokens: 340 },
  },
  {
    id: 17,
    builderUsername: "danakim",
    agentName: "Customer Support Agent",
    framework: "CrewAI",
    date: "Mar 19, 2026",
    overallScore: 4.4,
    agentTask: "Respond to a customer asking about return policy eligibility for a damaged item.",
    reviewer: "Leila Moss",
    experience: {
      goalCompletion: 4, helpfulness: 5, coherence: 4, factuality: 4, safety: 5,
      freeText: "Knew when to escalate and when not to. Slightly robotic phrasing in a couple responses.",
    },
    metrics: { latencyMs: 1100, costUsd: 0.005, toolCalls: 1, llmCalls: 1, errors: 0, pathEfficiency: 0.94, contextTokens: 3100, completionTokens: 380 },
  },
  {
    id: 18,
    builderUsername: "danakim",
    agentName: "Onboarding Assistant",
    framework: "CrewAI",
    date: "Mar 14, 2026",
    overallScore: 4.2,
    agentTask: "Walk a new user through setting up their account and completing their profile.",
    reviewer: "Chris Anand",
    experience: {
      goalCompletion: 4, helpfulness: 4, coherence: 5, factuality: 4, safety: 5,
      freeText: "Clear step-by-step instructions. Got confused when I skipped a step and tried to go back.",
    },
    metrics: { latencyMs: 1400, costUsd: 0.009, toolCalls: 3, llmCalls: 2, errors: 0, pathEfficiency: 0.88, contextTokens: 4900, completionTokens: 520 },
  },
  {
    id: 19,
    builderUsername: "danakim",
    agentName: "Feedback Analyzer",
    framework: "CrewAI",
    date: "Mar 11, 2026",
    overallScore: 3.7,
    agentTask: "Analyze 200 user feedback responses and surface the top themes and sentiment.",
    reviewer: "Maya Chen",
    experience: {
      goalCompletion: 4, helpfulness: 4, coherence: 3, factuality: 3, safety: 5,
      freeText: "Themes were roughly right but some were too broad to be actionable. Sentiment scoring felt off for sarcastic responses.",
    },
    metrics: { latencyMs: 8400, costUsd: 0.083, toolCalls: 12, llmCalls: 5, errors: 1, pathEfficiency: 0.74, contextTokens: 26300, completionTokens: 1860 },
  },
];